### ISSUE TITLE
BUG 🐞: Getting window size too small, in fullscreen mode

### ISSUE THREAD

**Issue by justinbather** [ajayd-san/gomanagedocker#21]
**Describe the bug**
When running the binary with my terminal (Alacritty) in fullscreen mode, I'm getting an error stating 'Window too small 43 x 158, Consider going fullscreen for optimal experience'. I have tried restarting multiple times, and tried resizing manually to fit screen (14" Macbook Pro)

**To Reproduce**
- Set Alacritty terminal to fullscreen
- Run binary with `gomanagedocker`

**Expected behavior**
To not get error, or at least not be blocked completely

**Screenshots**
<img width="1512" alt="Screenshot 2024-07-18 at 9 21 06 PM" src="https://github.com/user-attachments/assets/b21d0b8d-63bb-4617-adc7-7d960cfa7ea4">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - gmd Version: V1.3 (latest as of July 18, 2024)

**Additional context**
I can't escape out of it to get into the main view or anything, I have to just Ctrl-C to exit and can't use :(

I'd love to take on this issue if you don't have the time!

**Comment by ajayd-san** [comment]
Hey, 

This is not a bug it's a feature 🤡.  Initially while developing this I had to set height and width constraints to make sure the TUI doesn't break. For now, the minimum height and width needed are 33 and 169 respectively. Since, your setup doesn't meet those requirements, you will have to decrease the fontsize to meet the requirements. 

However, I plan on removing this constraint in the near future (probably next release 😁). In v1.3, I've updated the lists and infobox to update dynamically depending on the width of the window. And next setup would be adjust the height and hide/unhide infobox depending on the window height.

But yeah, unfortunately you will have to decrease your font size a bit (try decreasing just by 1 unit initially). If you prefer, you can do it in a different terminal if you don't want to change your font size of your main terminal. 

let me know if you have any other questions. I'm happy to help!

**Comment by justinbather** [comment]
Haha no worries lad, I'll just decrease my font-size and play around with it, I plan on using it for work over the next couple weeks, it's a really great idea, love the project!

**Comment by ajayd-san** [comment]
Thanks! I'm working on relaxing the window size constraints as we speak. I'm thinking of doing a v1.3.1 patch soon that will handle yours and a couple of other issues. 

Let me know how it is working out for you. I'd image there are a few bugs in circulation that need to be ironed out.

**Comment by ajayd-san** [comment]
Hey @justinbather!

I've pushed a patch that great improves how resizing is handled. You shouldn't have any issues now. Just get the new release using any of the methods. 

More importantly, you can go back to your original font size!

**Comment by justinbather** [comment]
Ahh good stuff. I’ll pull down latest, thanks!
________________________________
