### ISSUE TITLE
gmd requesting 2 versions of GLIBC

### ISSUE THREAD

**Issue by thinkbig1979** [ajayd-san/gomanagedocker#8]
Here's my terminal output after having followed the install instructions and then typing 'gmd' 

```bash
❯ gmd                                                                                                                                                                                       │
│gmd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by gmd)                                                                                                      
│gmd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by gmd) 
```

**Comment by ajayd-san** [comment]
Hey!

Can I get some more info about your setup?

I need: 
- Your Operating system
- kernel version
- glibc version (type `ldd --version` in your terminal)
- Processor architecture

**Comment by thinkbig1979** [comment]
Sure thing, here are the details you've asked for.

>>>>>
- ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31 

- Linux 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Distributor ID:	Ubuntu
- Description:	Ubuntu 20.04.6 LTS
- Release:	20.04
- Codename:	focal

**Comment by ajayd-san** [comment]
thanks for the info. 

The error seems pretty self-explanatory. The glibc version used while linking the binary is not present in your system.

In this case, you have two options: 

1.  You could download the version required (in this case `GLIBC_2.34` only, since glibc is backward compatible)
2.  Compile it yourself using `go install github.com/ajayd-san/gomanagedocker@v1.1.1`

I'd recommend the 2nd approach if you have go toolchain installed, it's much more easier and quicker. 

But thanks for bringing this to my attention, I'll build upcoming releases with an older version of glibc so that this doesn't happen again. 

Let me know if you need any more help. 

Cheers!

**Comment by ajayd-san** [comment]
@thinkbig1979 Hey, you can try installing gmd with the script now. It should work with your glibc as I'm now compiling release builds in a slightly older docker container (which uses an older glibc version). 

script: 
```
bash -c "$(curl -sLo- https://raw.githubusercontent.com/ajayd-san/gomanagedocker/main/install.sh)"
```

**Comment by thinkbig1979** [comment]
Works great, thank you @ajayd-san !
